export async function GET(request) {
  const responseData = {
    code: 200,
    status: 'SUCCESS',
    recordsTotal: 5,
    data: [
      {
        id: 'PJT-458163-1',
        name: 'Nama Project 1',
        description:
          'Postify is the SMM managemen t platform that lets them create a comprehensive social media strategy they can manage all in one place.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/demo-app-2.jpeg',
        productionUri: 'https://telkomuniversity.ac.id/',
        repositoryUri: 'https://github.com/sandhikagalih',
        budget: 1000000,
        createdAt: '2024-01-26 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-2',
        name: 'Nama Project 2',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 2500000,
        createdAt: '2022-02-26 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-3',
        name: 'Nama Project 3',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/demo-app-2.jpeg',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 500000,
        createdAt: '2023-04-15 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-4',
        name: 'Nama Project 4',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 750000,
        createdAt: '2023-07-02 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-5',
        name: 'Nama Project 5',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/demo-app-2.jpeg',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 600000,
        createdAt: '2023-09-18 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-6',
        name: 'Nama Project 6',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 850000,
        createdAt: '2023-11-05 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-7',
        name: 'Nama Project 7',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/demo-app-2.jpeg',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 700000,
        createdAt: '2024-01-20 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-8',
        name: 'Nama Project 8',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 450000,
        createdAt: '2024-03-14 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-9',
        name: 'Nama Project 9',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/demo-app-2.jpeg',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 900000,
        createdAt: '2024-04-29 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-10',
        name: 'Nama Project 10',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 550000,
        createdAt: '2024-06-11 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-11',
        name: 'Nama Project 11',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 400000,
        createdAt: '2023-05-08 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-12',
        name: 'Nama Project 12',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 650000,
        createdAt: '2023-08-22 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-13',
        name: 'Nama Project 13',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 800000,
        createdAt: '2023-10-29 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-14',
        name: 'Nama Project 14',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 950000,
        createdAt: '2024-02-12 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-15',
        name: 'Nama Project 15',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 700000,
        createdAt: '2024-04-06 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-16',
        name: 'Nama Project 16',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 550000,
        createdAt: '2024-05-19 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-17',
        name: 'Nama Project 17',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 450000,
        createdAt: '2024-07-24 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-18',
        name: 'Nama Project 18',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 850000,
        createdAt: '2024-09-03 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-19',
        name: 'Nama Project 19',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 950000,
        createdAt: '2024-10-15 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      },
      {
        id: 'PJT-458163-20',
        name: 'Nama Project 20',
        description:
          'Postify is the SMM management platform that lets them create a comprehensive social media strategy they can manage all in one place more that our universi on that face, in interstellar for our coming in the future wolrd in you hand.',
        iconUri: 'assets/uploads/projects/icons/logo-project.png',
        imageUri: 'assets/uploads/projects/thumbnails/projects-thumbnail.png',
        productionUri: 'https://www.cciunitel.com/',
        repositoryUri: 'https://github.com/angelabauer',
        budget: 500000,
        createdAt: '2024-12-28 21:28:37.261134+01:00',
        updatedAt: '2013-02-26 21:28:37.261134+01:00',
      }
    ],
    error: null,
  };
  return new Response(JSON.stringify(responseData));
}
